blank_issues_enabled: false
issue_template:
  - name: "Feature Request"
    description: "Propose a new feature or improvement."
    title: "[Feature]: "
    labels: ["enhancement"]
    body: "./issue_templates/feature_request.md"
  - name: "New Plush"
    description: "Propose a new feature or improvement."
    title: "[PLUSH]: "
    labels: ["New Plush"]
    body: "./issue_templates/new_plush.md"