package com.any.mikuplushie.datagen;

import com.any.mikuplushie.ModBlocks;
import com.any.mikuplushie.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.minecraft.data.server.recipe.RecipeJsonProvider;
import net.minecraft.data.server.recipe.ShapedRecipeJsonBuilder;
import net.minecraft.item.Items;
import net.minecraft.recipe.book.RecipeCategory;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;

public class ModRecipeProvider extends FabricRecipeProvider {

	public ModRecipeProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
		super(output);
	}

	@Override
	public void generate(Consumer<RecipeJsonProvider> exporter) {
		ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.CANUDINHO)
				.pattern("p")
				.pattern("p")
				.input('p', Items.PAPER)
				.criterion(FabricRecipeProvider.hasItem(Items.PAPER), FabricRecipeProvider.conditionsFromItem(Items.PAPER))
				.offerTo(exporter);


		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR)
				.pattern("cyc")
				.pattern("cgc")
				.input('c', Items.CYAN_WOOL)
				.input('y', Items.YELLOW_WOOL)
				.input('g', Items.GREEN_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BA)
				.pattern("crc")
				.pattern("cwc")
				.pattern("b  ")
				.input('c', Items.CYAN_WOOL)
				.input('r', Items.RED_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('b', Items.BLUE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BIK)
				.pattern("cwc")
				.pattern("cwc")
				.pattern("   ")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BEACH)
				.pattern("cyc")
				.pattern("cgc")
				.pattern("s  ")
				.input('c', Items.CYAN_WOOL)
				.input('y', Items.YELLOW_WOOL)
				.input('g', Items.GREEN_WOOL)
				.input('s', Items.SAND)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.SAND), FabricRecipeProvider.conditionsFromItem(Items.SAND))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BRAID)
				.pattern("cyc")
				.pattern("cgc")
				.pattern("b  ")
				.input('c', Items.CYAN_WOOL)
				.input('y', Items.YELLOW_WOOL)
				.input('g', Items.GREEN_WOOL)
				.input('b', Items.BLACK_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BA_DRUM)
				.pattern("crc")
				.pattern("cwc")
				.pattern("bn ")
				.input('c', Items.CYAN_WOOL)
				.input('r', Items.RED_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('b', Items.BLUE_WOOL)
				.input('n', Items.NOTE_BLOCK)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.NOTE_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.NOTE_BLOCK))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_PA)
				.pattern("cwc")
				.pattern("cwc")
				.pattern("i  ")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('i', Items.CORNFLOWER)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.CORNFLOWER), FabricRecipeProvider.conditionsFromItem(Items.CORNFLOWER))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_SP)
				.pattern("cwc")
				.pattern("crc")
				.pattern("bi ")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('r', Items.RED_WOOL)
				.input('b', Items.BLACK_WOOL)
				.input('i', Items.GRAY_CONCRETE)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_CONCRETE), FabricRecipeProvider.conditionsFromItem(Items.GRAY_CONCRETE))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_MG)
				.pattern("cwc")
				.pattern("cbc")
				.pattern("rg ")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('b', Items.BLACK_WOOL)
				.input('r', Items.RED_WOOL)
				.input('g', Items.GOLD_NUGGET)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GOLD_NUGGET), FabricRecipeProvider.conditionsFromItem(Items.GOLD_NUGGET))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BROWN_BRO)
				.pattern("cbc")
				.pattern("cBc")
				.pattern("i  ")
				.input('c', Items.CYAN_WOOL)
				.input('b', Items.BROWN_WOOL)
				.input('B', Items.BLACK_WOOL)
				.input('i', Items.IRON_NUGGET)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.IRON_NUGGET), FabricRecipeProvider.conditionsFromItem(Items.IRON_NUGGET))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_ELECTRICIAN)
				.pattern("cbc")
				.pattern("cBc")
				.pattern("r  ")
				.input('c', Items.CYAN_WOOL)
				.input('b', Items.BROWN_WOOL)
				.input('B', Items.BLUE_WOOL)
				.input('r', Items.REDSTONE)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.REDSTONE), FabricRecipeProvider.conditionsFromItem(Items.REDSTONE))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_BIK_ORANGE)
				.pattern("cwc")
				.pattern("coc")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('o', Items.ORANGE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.ORANGE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.ORANGE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_AM)
				.pattern("cwc")
				.pattern("coc")
				.pattern("bj ")
				.input('c', Items.CYAN_WOOL)
				.input('w', Items.WHITE_WOOL)
				.input('o', Items.RED_WOOL)
				.input('b', Items.BLUE_WOOL)
				.input('j', Items.JUNGLE_SAPLING)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.JUNGLE_SAPLING), FabricRecipeProvider.conditionsFromItem(Items.JUNGLE_SAPLING))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_FUT_FLA)
				.pattern("crc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('r', Items.RED_WOOL)
				.input('b', Items.BLACK_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_FUT_CAM)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.LIGHT_GRAY_WOOL)
				.input('b', Items.BLACK_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_GO)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.YELLOW_WOOL)
				.input('b', Items.GREEN_WOOL)
				.input('a', Items.LEAD)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LEAD), FabricRecipeProvider.conditionsFromItem(Items.LEAD))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_SCHOOL_PE)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.BLUE_WOOL)
				.input('a', Items.TUBE_CORAL_FAN)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.TUBE_CORAL_FAN), FabricRecipeProvider.conditionsFromItem(Items.TUBE_CORAL_FAN))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_FUT_CRVG)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.BLACK_WOOL)
				.input('a', Items.CARTOGRAPHY_TABLE)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.CARTOGRAPHY_TABLE), FabricRecipeProvider.conditionsFromItem(Items.CARTOGRAPHY_TABLE))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_BR_RS)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.GRAY_WOOL)
				.input('b', Items.RED_WOOL)
				.input('a', Items.MOSS_BLOCK)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.MOSS_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.MOSS_BLOCK))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_FROG)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.GRAY_WOOL)
				.input('b', Items.LIGHT_BLUE_WOOL)
				.input('a', Items.TADPOLE_BUCKET)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.TADPOLE_BUCKET), FabricRecipeProvider.conditionsFromItem(Items.TADPOLE_BUCKET))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_MUSHROOM)
				.pattern("clc")
				.pattern("cbc")
				.pattern("a  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.RED_WOOL)
				.input('b', Items.MOSS_BLOCK)
				.input('a', Items.RED_MUSHROOM_BLOCK)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.MOSS_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.MOSS_BLOCK))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_MUSHROOM_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.RED_MUSHROOM_BLOCK))
				.offerTo(exporter);


		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_SENBONZAKURA)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.GREEN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.CHERRY_LOG)
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.CHERRY_LOG), FabricRecipeProvider.conditionsFromItem(Items.CHERRY_LOG))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_URAOTOMELOVERS)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.BLACK_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_PERSONADANCING)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.BLACK_WOOL)
				.input('d', Items.NOTE_BLOCK)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.NOTE_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.NOTE_BLOCK))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_HELLOPLANET)
				.pattern("clc")
				.pattern("cbc")
				.pattern("de ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.IRON_BLOCK)
				.input('d', Items.LIME_WOOL)
				.input('e', Items.PURPLE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.IRON_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.IRON_BLOCK))
				.criterion(FabricRecipeProvider.hasItem(Items.LIME_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIME_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.PURPLE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.PURPLE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_HACHUNE)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.GRAY_WOOL)
				.input('d', Items.LILY_OF_THE_VALLEY)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LILY_OF_THE_VALLEY), FabricRecipeProvider.conditionsFromItem(Items.LILY_OF_THE_VALLEY))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_ZATSUNE)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.BLACK_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.RED_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_INFINITY)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.LIGHT_BLUE_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.GRAY_WOOL)
				.input('d', Items.ENDER_EYE)
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.ENDER_EYE), FabricRecipeProvider.conditionsFromItem(Items.ENDER_EYE))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_WEREWOMAN)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.LIGHT_GRAY_WOOL)
				.input('b', Items.BONE)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BONE), FabricRecipeProvider.conditionsFromItem(Items.BONE))
				.offerTo(exporter);


		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_VAMPIRE)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.RED_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.BLACK_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_JASON)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.BIRCH_PLANKS)
				.input('b', Items.BROWN_WOOL)
				.input('d', Items.IRON_SWORD)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BIRCH_PLANKS), FabricRecipeProvider.conditionsFromItem(Items.BIRCH_PLANKS))
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.IRON_SWORD), FabricRecipeProvider.conditionsFromItem(Items.IRON_SWORD))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_MICHAEL_MYERS)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.BROWN_WOOL)
				.input('l', Items.GRAY_WOOL)
				.input('b', Items.BLUE_WOOL)
				.input('d', Items.IRON_SWORD)
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.IRON_SWORD), FabricRecipeProvider.conditionsFromItem(Items.IRON_SWORD))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_PUMPKIN)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.WHITE_WOOL)
				.input('b', Items.LIGHT_GRAY_WOOL)
				.input('d', Items.PUMPKIN)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_GRAY_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.PUMPKIN), FabricRecipeProvider.conditionsFromItem(Items.PUMPKIN))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_GHOSTFACE)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.BIRCH_PLANKS)
				.input('b', Items.BLACK_WOOL)
				.input('d', Items.IRON_SWORD)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BIRCH_PLANKS), FabricRecipeProvider.conditionsFromItem(Items.BIRCH_PLANKS))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.IRON_SWORD), FabricRecipeProvider.conditionsFromItem(Items.IRON_SWORD))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_FRANKENSTEIN)
				.pattern("clc")
				.pattern("cbc")
				.pattern("d  ")
				.input('c', Items.BROWN_WOOL)
				.input('l', Items.GREEN_WOOL)
				.input('b', Items.BLACK_WOOL)
				.input('d', Items.LIGHTNING_ROD)
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHTNING_ROD), FabricRecipeProvider.conditionsFromItem(Items.LIGHTNING_ROD))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_MUMMY)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.BLACK_WOOL)
				.input('l', Items.BONE_BLOCK)
				.input('b', Items.PAPER)
				.criterion(FabricRecipeProvider.hasItem(Items.BLACK_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BLACK_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BONE_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.BONE_BLOCK))
				.criterion(FabricRecipeProvider.hasItem(Items.PAPER), FabricRecipeProvider.conditionsFromItem(Items.PAPER))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_GHOST)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_STAINED_GLASS)
				.input('l', Items.WHITE_STAINED_GLASS)
				.input('b', Items.LIGHT_GRAY_STAINED_GLASS)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_STAINED_GLASS), FabricRecipeProvider.conditionsFromItem(Items.CYAN_STAINED_GLASS))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_STAINED_GLASS), FabricRecipeProvider.conditionsFromItem(Items.WHITE_STAINED_GLASS))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_GRAY_STAINED_GLASS), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_GRAY_STAINED_GLASS))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_PATATI)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.YELLOW_WOOL)
				.input('l', Items.LIGHT_BLUE_WOOL)
				.input('b', Items.WHITE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_BLUE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_BLUE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_PATATA)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.YELLOW_WOOL)
				.input('l', Items.LIME_WOOL)
				.input('b', Items.RED_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.YELLOW_WOOL), FabricRecipeProvider.conditionsFromItem(Items.YELLOW_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIME_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIME_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_DEVIL)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.MAGMA_BLOCK)
				.input('l', Items.NETHERRACK)
				.input('b', Items.LIGHT_GRAY_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.MAGMA_BLOCK), FabricRecipeProvider.conditionsFromItem(Items.MAGMA_BLOCK))
				.criterion(FabricRecipeProvider.hasItem(Items.NETHERRACK), FabricRecipeProvider.conditionsFromItem(Items.NETHERRACK))
				.criterion(FabricRecipeProvider.hasItem(Items.LIGHT_GRAY_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIGHT_GRAY_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_WITCH)
				.pattern("clc")
				.pattern("cbc")
				.pattern("de ")
				.input('c', Items.PURPLE_WOOL)
				.input('l', Items.SPYGLASS)
				.input('b', Items.GREEN_WOOL)
				.input('d', Items.STICK)
				.input('e', Items.WHEAT)
				.criterion(FabricRecipeProvider.hasItem(Items.PURPLE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.PURPLE_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.SPYGLASS), FabricRecipeProvider.conditionsFromItem(Items.SPYGLASS))
				.criterion(FabricRecipeProvider.hasItem(Items.GREEN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.GREEN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.STICK), FabricRecipeProvider.conditionsFromItem(Items.STICK))
				.criterion(FabricRecipeProvider.hasItem(Items.WHEAT), FabricRecipeProvider.conditionsFromItem(Items.WHEAT))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_SANTA)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.RED_WOOL)
				.input('b', Items.WHITE_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.WHITE_WOOL), FabricRecipeProvider.conditionsFromItem(Items.WHITE_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_REINDEER)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.BROWN_WOOL)
				.input('b', Items.RED_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.BROWN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.BROWN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_SANTA_ELF)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.LIME_WOOL)
				.input('b', Items.RED_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.LIME_WOOL), FabricRecipeProvider.conditionsFromItem(Items.LIME_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.offerTo(exporter);

		ShapedRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.MIKU_PLUSH_XMAS_TREE)
				.pattern("clc")
				.pattern("cbc")
				.input('c', Items.CYAN_WOOL)
				.input('l', Items.SPRUCE_LEAVES)
				.input('b', Items.RED_WOOL)
				.criterion(FabricRecipeProvider.hasItem(Items.CYAN_WOOL), FabricRecipeProvider.conditionsFromItem(Items.CYAN_WOOL))
				.criterion(FabricRecipeProvider.hasItem(Items.SPRUCE_LEAVES), FabricRecipeProvider.conditionsFromItem(Items.SPRUCE_LEAVES))
				.criterion(FabricRecipeProvider.hasItem(Items.RED_WOOL), FabricRecipeProvider.conditionsFromItem(Items.RED_WOOL))
				.offerTo(exporter);
	}
}
